config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/metroadmin', as: 'rails_admin'
  resources :news,only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :partners, only: [:show]
  resources :projects, only: [:index, :show]

  root 'home#index'
  get 'technical' => 'technical#index'
  get 'map' => 'map#index'
  get 'about-us' => 'home#about_us'

end

app/views/layouts/shared/_footer.html.erb
<footer itemscope="" itemtype="http://schema.org/WPFooter">
  <div class='row'>
    <div class='small-12'>
      <%= image_tag 'logo.png', class: 'float-left' %>
      <%= content_tag :ul, class: 'float-left upper' do %>
        <%= render partial: 'layouts/shared/menu_list' %>
      <% end %>
      <ul class='social-list float-right'>
        <li>
          <a href="https://www.facebook.com/Metroreklama" class="social facebook"></a>
          <a href="https://www.instagram.com/metroreklama/" class="social instagram"></a>
          <a href="https://www.linkedin.com/company/metroreklama/" class="social linkedin"></a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/shared/_head.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport">

<%= favicon_link_tag 'favicon.ico' %>

<%= favicon_link_tag asset_url('app_icons/apple-icon-32x32.png'),  rel: 'apple-touch-icon', type: 'image/png', sizes: '32x32'%>
<%= favicon_link_tag asset_url('app_icons/apple-icon-57x57.png'),  rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57'%>
<%= favicon_link_tag asset_url('app_icons/apple-icon-72x72.png'),  rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72' %>
<%= favicon_link_tag asset_url('app_icons/apple-icon-114x114.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
<%= favicon_link_tag asset_url('app_icons/apple-icon-144x144.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144' %>
<%= favicon_link_tag asset_url('app_icons/android-icon-36x36.png'),  rel: 'icon', type: 'image/png', sizes: '36x36' %>
<%= favicon_link_tag asset_url('app_icons/android-icon-72x72.png'),  rel: 'icon', type: 'image/png', sizes: '72x72' %>
<%= favicon_link_tag asset_url('app_icons/android-icon-96x96.png'),  rel: 'icon', type: 'image/png', sizes: '96x96' %>
<%= favicon_link_tag asset_url('app_icons/android-icon-192x192.png'), rel: 'icon', type: 'image/png', sizes: '192x192' %>

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= asset_url('app_icons/ms-icon-144x144.png') %>">
<meta name="theme-color" content="#ffffff">

<!--
<link rel="canonical" href="<%#= @page[:url]%>"/>

<title><%#= "#{@page[:title]} | #{@page[:site_name]}"%></title>
<meta name="description" content="<%#= @page[:description]%>"/>
<meta name="keywords" content="<%#= @page[:keywords] %>" />

<meta property="og:site_name"   content="<%#= @page[:site_name]%>"/>
<meta property="og:locale"      content="bg_BG"/>
<meta property="og:image"             content="http://metroreklama.com<%#= @page[:image]%>"/>
<meta property="og:image:secure_url"  content="http://metroreklama.com<%#= @page[:image]%>">
<meta property="og:image:type"        content="image/png">
<meta property="og:title"             content="<%#= @page[:title]%>" />
<meta property="og:description"       content="<%#= @page[:description]%>"/>
<meta property="og:url"               content="<%#= @page[:url]%>" />
<meta property="og:type"              content="article" />

<meta name="twitter:url" content="<%#= @page[:url]%>">
<meta name="twitter:title" content="<%#= @page[:title]%>">
<meta name="twitter:description" content="<%#= @page[:description]%>">
<meta name="twitter:image:src" content="http://metroreklama.com<%#= @page[:image]%>"> -->

<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%== meta_data_tags %>

<script type="application/ld+json">
  {
    "@context" : "http://schema.org",
    "@type" : "Organization",
    "name" : "metroreklama",
    "url" : "http://metroreklama.com/",
  }
</script>

app/views/layouts/shared/_header.html.erb
<nav id="main-menu" itemscope itemtype="http://schema.org/SiteNavigationElement" class="fixed <%= 'visible-menu' if @visible_menu %>">
  <div class='row'>
    <div class="top-bar-section big small-12">
      <!-- Right Nav Section -->
      <ul class="float-left">
        <li class="">
          <a href="/" class="logo">metroreklama.com</a>
        </li>
      </ul>
      <ul class="float-right">
        <li>
          <div class='float-left' style='padding-right:15px;line-height:60px;'>
            <% if locale.to_s == 'en' %>
              <%= link_to 'BG', '?locale=bg', class: 'strong font-24' %>
            <% else %>
               <%= link_to 'EN', '?locale=en', class: 'strong font-24' %>
            <% end %>
          </div>
          <button class="hamburger hamburger--spin" type="button">
            <span class="hamburger-box">
              <span class="hamburger-inner"></span>
            </span>
          </button>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="dropdown-menu">
  <div class="text-center menu">
    <ul class="small-block-grid-1">
      <%= render partial: 'layouts/shared/menu_list' %>
      <li>  
        <ul class='social-list'>
          <li>
            <a href="https://www.facebook.com/Metroreklama" class="social facebook"></a>
            <a href="https://www.instagram.com/metroreklama/" class="social instagram"></a>
            <a href="https://www.linkedin.com/company/metroreklama/" class="social linkedin"></a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/shared/_menu_list.html.erb
<%= content_tag :li, link_to(t('menu.home'), '/') %>
<%= content_tag :li, link_to(t('menu.about_us'), '/about-us') %>
<%= content_tag :li, link_to(t('menu.advertising'), categories_path) %>
<%= content_tag :li, link_to(t('menu.formats'), projects_path) %>
<%= content_tag :li, link_to(t('menu.map'), '/map') %>
<%= content_tag :li, link_to(t('menu.news'), news_index_path ) %>
<%= content_tag :li, link_to(t('menu.contacts'), new_contact_path) %>
<%= content_tag :li, link_to(t('menu.tech'), '/technical') %>

app/views/layouts/shared/_partners.html.erb
<% partners = Partner.where(show_on_homepage: true) %>
<div class='home-partners-list content-wrapper'>
  <div class='row'>
    <%= content_tag :span, content_tag(:span, raw(t('home.index.our_partners')), class: 'font-16') %>
    <div class="flickity-brands" data-flickity data-equalizer>
      <% partners.each do |partner|%>
        <%#= image_tag(partner.logo(:original)) %>
        <div class="carousel-cell float-left wallpaper" data-equalizer-watch style="background-image:url(<%= partner.logo(:original)%>)">
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">

$(function(){ 
  var flky = new Flickity( '.flickity-brands', {
    autoPlay: true,
    cellAlign: 'left',
    pageDots: false,
    resize: false,
    freeScroll: true,
    prevNextButtons: false,
    contain: false
  });
});
</script>